### ISSUE TITLE
Transcripts never finishes- (inside assemblyai get retry interval: checking transcript update)

### ISSUE THREAD

**Issue by zhanming-wang** [pietrop/digital-paper-edit-electron#45]
**Describe the bug**
Transcripts run forever. It's been several hours. 

**To Reproduce**
I'm using batch transcripts of 4 hour-long videos. AssemblyAI, defult. 

**Expected behavior**
Transcript finishes within one hour. 

**Screenshots**
![Screen Shot 2020-05-19 at 10 15 40 PM](https://user-images.githubusercontent.com/20973963/82407573-54c34080-9a1e-11ea-8032-2d978e29fa7c.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Version 1.2.10 (1.2.10.213)

**Comment by pietrop** [comment]
@zhanming-wang I noticed you closed this issue? Where you able to figure it out?
