### ISSUE TITLE
IBM Watson STT

### ISSUE THREAD

**Issue by pietrop** [pietrop/digital-paper-edit-electron#51]
**Is your feature request related to a problem? Please describe.**

Speechmatics is discontinuing their web portal, meaning the access to STT with API key will no longer be supported, from 30th of Sept 2020. See their [deprecation notice for more details](
https://www.speechmatics.com/transcription-web-portal-deprecation-notice).

**Describe the solution you'd like**

Have an alternative to be able to still cater for languages other than English, eg Italian.

**Describe alternatives you've considered**

autoEdit 2 used to have support for IBM Watson. So thinking of bringing that back.

- https://github.com/OpenNewsLabs/autoEdit_2/pull/50
- https://github.com/OpenNewsLabs/autoEdit_2/issues/85
- https://github.com/OpenNewsLabs/autoEdit_2/pull/91
- https://github.com/OpenNewsLabs/autoEdit_2/pull/96

**Note:** Only annoying thing is that IBM requires to add credit card details even for the free trial of the pay as you go option.

**Additional context**

- [IBM Watson STT API Reference docs](https://cloud.ibm.com/apidocs/speech-to-text?code=node)

**Comment by johnfelipe** [comment]
will be possible have this API in next v3 releases?
i want to test spanish version API, and only ibm is good in autoedit2

**Comment by pietrop** [comment]
we are still waiting on IBM to sort out their SDK. @seanmtracey might have some updates?

**Comment by johnfelipe** [comment]
None advance with Watson IBM to Spanish language?

**Comment by pietrop** [comment]
Hey @johnfelipe 
Unfortunately no. And I don't quiet even enough time at the moment to look into it. But would welcome PRs and could advise if anyone else has got capacity to dig into it.
