### ISSUE TITLE
Mark as Abandonware

### ISSUE THREAD

**Issue by Erudition** [pietrop/digital-paper-edit-electron#96]
The website is down and the domain autoedit.io is up for sale. The gitbook and the repo haven't been updated in years, it appears. Time to call it dead?

**Comment by pietrop** [comment]
Website is now available at https://pietropassarelli.net/autoedit

Some extra context:
- This has always been a passion project, but given it generates no revenue it makes no sense for me front the yearly custom domain costs.
- I know some folks are still using this as part of their day to day audio/video production with real impact on their work. 
- And I also know is relatively stable (in the core user journey 🤞) 
- therefore am keeping it open in a "a case by case maintenance mode" in case any major bugs 🐛 were to come up (with the possibility of a "best effort" solution, when and if time allows).
